### ISSUE TITLE
Some slurm commands in the doc don't work on Mila's cluster

### ISSUE THREAD

**Issue by achillemyette1** [mila-iqia/mila-docs#12]
(This issue was originally raised by user **bordesf** in the previous repository "AI-HPC-Docs" - on Jan 20, 2021)

bordesf commented on Jan 20
So, we have a single tutorial on Slurm but some commands doesn't work on the Mila cluster, like:
salloc –gres=gpu -c 2 –mem=12000

On the mila cluster, we should specify the number of gpu with salloc --gres=gpu:1 -c 2 --mem=12000.

Also sacct -u my_username --start=20190101 doesn't work, we need to use:
sacct -u my_username --start=2019-01-01

So at some point, it should be worth to through all the commands and see if they are working as expected on both cluster (And add a warning if one command works only on one specific cluster).

**Comment by btravouillon** [comment]
Reopen as per @tesfaldet comment.

**Comment by satyaog** [comment]
https://github.com/mila-iqia/mila-docs/commit/63ab7de3600424f19f1ce27fb15f5ae2263c2045 should have fixed it (done right after @tesfaldet comment)
