### ISSUE TITLE
Add section on remote SSH through VS Code

### ISSUE THREAD

**Issue by tesfaldet** [mila-iqia/mila-docs#16]
There are plenty of students wanting to remotely develop on the cluster using VS Code's Remote SSH extension. The reason being that it offers remote debugging capabilities in a flexible IDE, which can prove invaluable for rapid prototyping. I suggest a section to be added on using VS Code with the cluster. I can contribute the first PR if need be.

**Comment by tesfaldet** [comment]
Below is a copy-paste of my explanation of getting this working with a student on Slack. Mind the weird sentence structuring...

Save this file in your home directory `$HOME/dev_env.sh`

```
#!/bin/bash
#SBATCH --job-name=dev_env
#SBATCH --ntasks=1
#SBATCH --mem=12Gb
#SBATCH --cpus-per-task=2
#SBATCH --gres=gpu:1
#SBATCH --output=%x_%A.out
#SBATCH --error=%x_%A.err
​
tail -f /dev/null
```

To use this, first you have to make the script executable. `chmod +x $HOME/dev_env.sh`. Then, run `sbatch $HOME/dev_env.sh` from a login node (`ssh -p 2222 <user>@login.server.mila.quebec`) This will request a job with the bash code `tail -f /dev/null` to be executed by a compute node. What this does is make the job never stop until it is pre-empted, but don’t worry it’s not a busy wait so it’s not wasting any resources. Once the job starts, you can connect to its node from within the login node or even locally on your home machine. To connect from within the login node, `ssh <compute node hostname>`. To connect locally from home, `ssh -J <user>@login.server.mila.quebec:2222 <user>@<compute node hostname>`.

To connect locally from home but through VS Code’s Remote SSH extension, add this in your local ssh config file (`~/.ssh/config`)

```
Host mila_login
    HostName login.server.mila.quebec
    User <user>
    Port 2222
    PreferredAuthentications publickey,keyboard-interactive
    ServerAliveInterval 120
    ServerAliveCountMax 5
Host mila_compute
    HostName <compute node hostname>
    User <user>
    ProxyJump mila_login
```

Then using the Remote SSH VS Code extension, connect to the host `mila_compute`

Also, if you have this ssh config file setup this way, you can also do `ssh mila_compute` instead of `ssh -J <user>@login.server.mila.quebec:2222 <user>@<compute node hostname>` if you want to connect via your terminal.

Oh, and to get the compute node hostname after you’ve launched your job, run `squeue -u $USER` in the login node.

```
mattie.tesfaldet@login-4:~$ squeue -u $USER
   JOBID     USER    PARTITION           NAME  ST START_TIME             TIME NODES CPUS TRES_PER_N MIN_MEM NODELIST (REASON) COMMENT
  935625 mattie.t         long        dev_env   R 2021-05-20T23:29 4-13:22:21     1    2      gpu:1     12G cn-a010 (None) (null)
```

Under `NODELIST` you can see the hostname, `cn-a010`

Its fully-qualified name is cn-`a010.server.mila.quebec`

[Here's](https://docs.mila.quebec/mila-cluster/nodes.html) the list of compute nodes mila has.

Also, an issue you’ll find when ssh’ing into the compute node is that the environment variable `$SLURM_TMPDIR` isn’t passed over to your environment. In the mila docs, you’ll see them recommend using this temp directory for temporarily storing the dataset the compute node will be using. This is because `$SLURM_TMPDIR` is supposed to point to the compute node’s local SSD. So it’s a very important env variable to have. To fix this issue, you’ll have to add this to `~/.bashrc`

```
# Bash interactive settings such as aliases, functions, completion, key bindings (that aren't in .inputrc)
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile
```

Also add this to `~/.profile`

```
# Environment variables and other session settings

# since ssh'ing into a running job's node doesn't have the SLURM_TMPDIR
# variable set for some reason (TODO: look into it)
export SLURM_TMPDIR=/Tmp/slurm.$SLURM_JOB_ID.0

# load the miniconda module
module load miniconda/3
```

Umm and just in case, add this to `~/.bash_profile`

```
# [[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile
if [[ $- == *i* ]]; then . ~/.bashrc; fi # Load .bashrc if the shell is interactive
```

Now in your pytorch code, if you wanna use a dataset, first copy it to `$SLURM_TMPDIR` then access it in your code with `os.environ.get`

I believe datasets are typically stored in `/network/datasets`

Btw I’m currently experiencing issues with debugging for some reason. It just started happening last night. Basically when I start a debug process with VS Code, it times out and says “waiting for debugee”

Oh, and add this to your `settings.json` file in your local VS Code (press cmd+shift+P on mac or ctrl+shift+P on windows/linux and type “open settings (json)“):

```
"terminal.integrated.defaultProfile.linux": "bash",
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash",
            "args": ["--login"]
        },
        "zsh": {
            "path": "zsh"
        },
        "fish": {
            "path": "fish"
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
        "pwsh": {
            "path": "pwsh",
            "icon": "terminal-powershell"
        }
    }
```

The `"bash"` setting is the important part because it adds the `--login` argument when you’re opening up a new terminal with the remote SSH extension. This login argument means that every new terminal that gets opened from within VS Code will start an interactive login shell. This will cause `.bashrc` to execute on the compute (and login) node, which will set up your user environment and set `$SLURM_TMPDIR`

**Comment by vict0rsch** [comment]
Interesting read. I thinks this makes an even stronger case for a jupyterlab app as they do at compute canada https://docs.computecanada.ca/wiki/JupyterLab

Reason is: I think many (most?) would feel this is really complex for such an apparently simple request, that is coding on the cluster

**Comment by tesfaldet** [comment]
Agreed, it is fairly complex to set up for new students. Which is why going the JupyterLab approach would be nice. However, I also think having this approach as an option would still be useful. Sometimes I just don't want to use JupyterLab ¯\_(ツ)_/¯

**Comment by vict0rsch** [comment]
Yes, this is definitely useful, but should not be the default recommendation for new comers

**Comment by tesfaldet** [comment]
Just putting this here for posterity:

When connecting to a compute node via the Remote SSH extension in vs code from multiple computers at once (e.g., using vs code on my mac mini and on my MacBook to connect to kepler3 and mila01, respectively), an issue will arise where one of the VS Code instances will close with the message "cannot reconnect." This is because VS Code's Remote SSH extension installs all necessary vs code server files under ~/.vscode-server. This folder contains the nodejs server and the extensions installed by the user. When you connect to a host through the Remote SSH extension in VS Code, it will attempt to communicate with VS Code Server running in the compute node. It will also put a lock on certain files in the `~/.vscode-server` folder. Since `~/.vscode-server` is hosted on an NFS (the user's home directory), then issues will arise when attempting to connect to VS Code Server from another VS Code instance/client. To fix this, change this setting in your VS Code `settings.json` file:

```
"remote.SSH.lockfilesInTmp": true
```

This will store all necessary lockfiles in the `/tmp` in the compute node instead of at `~/.vscode-server`

**Comment by tesfaldet** [comment]
Another tip:

Sometimes the compute nodes can be super slow. This can cause the VS Code debugger to timeout when starting a remote debug process. The debugger at the client-side is waiting for the debuggee at the server-side to respond. The debuggee is spawned as a subprocess at the compute node by the debugpy launcher ([debugpy](https://github.com/microsoft/debugpy) is the name of the VS Code python debugger) which is also running at the compute node. Sometimes the compute nodes can be so slow to spawn the debuggee subprocess that the debugpy launcher times out waiting for its creation. This can be alleviated by adding this to your `~/.profile`:

```
# for vs code debugging since the compute nodes can take a long time
# to spawn the debugpy debuggee
export DEBUGPY_PROCESS_SPAWN_TIMEOUT=500
```

This is just a temporary solution. I still need to figure out what's causing the significant slow downs at the compute nodes. It's happened on most of them so far. For example, even importing torch takes almost a minute.
