### ISSUE TITLE
Clarify the explanation of netdata and what it's presenting the user

### ISSUE THREAD

**Issue by tesfaldet** [mila-iqia/mila-docs#18]
Under the '[Monitoring](https://docs.mila.quebec/mila-cluster/monitoring/index.html)' section in the documentation, it explains that netdata "allow[s] you to check the resource usage of your model and identify bottlenecks." This is not true. Netdata is showing the user the resource usage of the node. Sometimes other users may be using that node, making it difficult to figure out your model's impact on the node.

**Comment by fosterrath-mila** [comment]
It seems this ticket is outdated.

**Comment by achillemyette1** [comment]
Please see new page about netdata -> https://docs.mila.quebec/Information.html?highlight=netdata
