### ISSUE TITLE
New "Distributed Training" section in "Minimal Examples" doesn't show up in docs page 

### ISSUE THREAD

**Issue by lebrice** [mila-iqia/mila-docs#183]
Also, even in this build from #182  (https://mila-docs--182.org.readthedocs.build/en/182/Minimal_examples.html#distributed-training), the three sub-pages don't appear:

![image](https://user-images.githubusercontent.com/13387299/235774498-91e99e0d-5230-493b-9df7-46c85e789023.png)

**Comment by satyaog** [comment]
I'm not sure where it breaks but the readthedocs here : https://mila-docs.readthedocs.io/en/latest/ seams to have the latest version. @btravouillon , where does https://docs.mila.quebec/ point to?

**Comment by btravouillon** [comment]
There is an issue with the CI/CD -> https://github.com/mila-iqia/mila-docs/actions/runs/4854780226/jobs/8696447156
