### ISSUE TITLE
Guidelines on internal collaborations and file-system sharing

### ISSUE THREAD

**Issue by vict0rsch** [mila-iqia/mila-docs#19]
We need to have a procedure to share a directory with collaborators at Mila.

This would basically mean having a procedure to create or request the creation of a directory (tmp1? home? to be discussed) to which all members of a group have identical rwx rights

Use-case is: I'm collaborating with other researchers, how are we supposed to work together w.r.t. the filesystem? What should one do to get a directory to share "data" (!= dataset)?

**Comment by tesfaldet** [comment]
Other researchers from within mila or outside of mila? Two very different scenarios.

**Comment by vict0rsch** [comment]
Internal, so ppl with an account on our cluster

**Comment by tesfaldet** [comment]
Perhaps following the [Compute Canada](https://docs.computecanada.ca/wiki/Sharing_data) approach would be useful. Having the mila ecosystem be as similar as possible to the compute canada ecosystem would make it easier for students to jump back and forth between the two.

**Comment by satyaog** [comment]
New doc should now cover this topic
