### ISSUE TITLE
Improve Jupyterhub filesystem exploration

### ISSUE THREAD

**Issue by vict0rsch** [mila-iqia/mila-docs#20]
We currently can't go "below" our home directory. For instance the jupyterlab file explorer on the left can't go and explore/create files (through the GUI) in miniscratch, tmp1 or slurm_tmpdir

**Comment by tesfaldet** [comment]
Should this be a support ticket instead? Doesn't seem to be related to the docs.

**Comment by vict0rsch** [comment]
True ; BUT I think the ticket system is too opaque and individual for "feature requests"
