### ISSUE TITLE
Mila cluster monitoring page is outdated

### ISSUE THREAD

**Issue by oscmansan** [mila-iqia/mila-docs#21]
I tried to access the monitoring page of a specific cluster node by navigating to `<node>.server.mila.quebec:19999`, as explained in https://docs.mila.quebec/mila-cluster/monitoring/index.html. However, this doesn't seem to work anymore, as my browser throws a DNS error.

As a workaround, @satyaog suggested to use this node health page for monitoring: https://dashboard.server.mila.quebec/d/vP_v3QDmk/node-health.

**Comment by satyaog** [comment]
Thank you for reporting this issue. It seams Graphana was just updated and the service page is now https://dashboard.server.mila.quebec/d/_1S05sQZk/service-nodes-health. @fosterrath-mila , @btravouillon , is that correct?

**Comment by satyaog** [comment]
Should now be covered in the new doc

**Comment by btravouillon** [comment]
Covered in https://docs.mila.quebec/Information.html#monitoring

> For every node, there is a web interface from Netdata itself at \<node>.server.mila.quebec:19999. This is accessible only when using the Mila wifi or through SSH tunnelling.
