### ISSUE TITLE
Overleaf licenses should be mentioned in the documentation

### ISSUE THREAD

**Issue by gyom** [mila-iqia/mila-docs#239]
This issue was added in the context of this Slack exchange.
https://mila-umontreal.slack.com/archives/CLETJK7TL/p1700144699035409

At the current time, there is no mention of how students should have access to Overleaf. The fact is that they have many ways to get standard or premium versions for free, and only one of those alternatives is through Mila.

I would expect that somewhere in the documentation that information should be there.

**Comment by btravouillon** [comment]
Do some users require an overleaf license to run jobs on the cluster?

**Comment by gyom** [comment]
No, there is no intersection between the use of Overleaf and the compute clusters.

I think I know what you're getting at, but I'll let you say it. :)

**Comment by btravouillon** [comment]
This is already documented in the Intranet. I added the link to the Slack conversation.

If this is not cluster related, that should not be documented in this project imho.

**Comment by gyom** [comment]
Hmm. I see your point here, and I'd be okay with omitting mentions of Overleaf on docs.mila.quebec. However, I think the entry in the Mila intranet would benefit from having some of the information from the UdeM accounts there as well.

I know we're not in the business of naming all the perks of all the universities of all students, but it does paint a limited picture of the situation when we mention only licences from Mila and we don't even mention that UdeM students get it for free (thus saving Mila a few hundreds of dollars).

The first thing that I would say to a UdeM student would be to get it from UdeM. If the Mila intranet doesn't say that ... it's not really giving the same quality of useful advice that we'd give in person (or on Slack).

**Comment by btravouillon** [comment]
I do agree we could add more information to the Intranet. We should discuss this outside of GH.
