### ISSUE TITLE
Non-bash shells guidelines

### ISSUE THREAD

**Issue by achillemyette1** [mila-iqia/mila-docs#3]
(This issue was originally raised by user **vict0rsch** in the previous repository "AI-HPC-Docs" - on Oct 24, 2019)

@vict0rsch
vict0rsch commented on Oct 24, 2019
I recently had issues with using zsh (and oh-my-zsh) on the mila cluster.

I guess not using bash is fairly common and therefore we'd need guidelines and good practices regarding how to set it up so that it does not mess with jobs, jupyterhub and whatnot

@vict0rsch
Author
vict0rsch commented on Oct 24, 2019
if I had this knowledge I'd do it but I can't :)

@vict0rsch
Author
vict0rsch commented on Feb 7, 2020
@qlux can you help here?

@qlux
qlux commented on Feb 7, 2020
Thanks Victor, I add this for next week !
Regards

**Comment by btravouillon** [comment]
We don't support zsh on the Mila cluster.
