### ISSUE TITLE
Consider using BACKGROUND KNOWLEDGE instead of CLUSTER THEORY header

### ISSUE THREAD

**Issue by satyaog** [mila-iqia/mila-docs#49]
![Screen Shot 2021-08-07 at 3 16 12 PM](https://user-images.githubusercontent.com/5014902/128611572-0b1cd20a-6bb7-4ddc-9d99-4465615d0643.png)
Might I suggest changing "CLUSTER THEORY" to "BACKGROUND KNOWLEDGE". You don't have to, I just find it less redundant than having "CLUSTER THEORY" followed by "General Cluster theory". It also opens the door for more articles to be placed under that section that don't necessarily need to be under "General Cluster theory"

_Originally posted by @tesfaldet in https://github.com/mila-iqia/mila-docs/issues/46#issuecomment-894696087_

**Comment by btravouillon** [comment]
This has been changed to "GENERAL THEORY" with a2a77bb7.
The "General Cluster theory" was removed.
