### ISSUE TITLE
Compute Canada priority clarification 

### ISSUE THREAD

**Issue by achillemyette1** [mila-iqia/mila-docs#5]
(This issue was originally raised by user **vict0rsch** in the previous repository "AI-HPC-Docs" - on Mar 6, 2020)

@vict0rsch
vict0rsch commented on Mar 6, 2020
Could you add a description of how priority allocation works on CC? Mainly regarding the differences with Mila's cluster

thinking about --qos or --partition: describing how irrelevant or different they are CC vs MC

@vict0rsch
Author
vict0rsch commented on Mar 6, 2020 • 
Only mention of priority is

Note that we do have a high priority for GPU jobs, but not for CPU jobs

which would require a couple more sentences. At least something like

jobs aren't assigned specifically by the user but rather by the scheduler based on the resources requested by the user (and resources available in partitions) (Xavier)

+ "You therefore don't need to specify qos or partition

**Comment by bouthilx** [comment]
Not sure how this should be mentioned in new version of the doc (currently branch `sprint_1`). The documentation for CC is clearly separated from Mila cluster and does not refer to Mila cluster documentation, only to CC documentation.
