### ISSUE TITLE
Provide a link to some SSH tunnelling guide

### ISSUE THREAD

**Issue by satyaog** [mila-iqia/mila-docs#51]
![Screen Shot 2021-08-07 at 3 44 27 PM](https://user-images.githubusercontent.com/5014902/128612175-d13dbfc7-233b-4988-8a3e-eb2feefec9ef.png)
Change to "only when using the Mila wifi or through SSH tunnelling". Provide a link to some SSH tunnelling guide.

_Originally posted by @tesfaldet in https://github.com/mila-iqia/mila-docs/issues/46#issuecomment-894699291_

**Comment by btravouillon** [comment]
We can add an example like `ssh -L19999:<node>.server.mila.quebec:19999 -p 2222 login.server.mila.quebec` and a link to http://localhost:19999.
Anyone who want to know more about "SSH tunneling" should be able to use their favorite search engine. (URLs on the Internet change every now and then, we can't deal with this in the long run).

**Comment by fosterrath-mila** [comment]
Peut-on matérialiser le commentaire de Bruno dans un PR ?

**Comment by satyaog** [comment]
Closed as this was covered in #76
