### ISSUE TITLE
Check if the Docker root issue can be by-passed using the rootless mode

### ISSUE THREAD

**Issue by satyaog** [mila-iqia/mila-docs#58]
![Screen Shot 2021-08-07 at 5 28 25 PM](https://user-images.githubusercontent.com/5014902/128614281-22d721d3-cee3-4024-8b7f-ec06eaf2a9b0.png)
I thought the whole root issue was dealt with? https://itnext.io/docker-running-in-rootless-mode-bdbcfc728b3a

_Originally posted by @tesfaldet in https://github.com/mila-iqia/mila-docs/issues/46#issuecomment-894709138_

**Comment by fosterrath-mila** [comment]
Currently there is no workaround deployed on our cluster for rootless docker.
