### ISSUE TITLE
Link to support ticket page when mentionned

### ISSUE THREAD

**Issue by satyaog** [mila-iqia/mila-docs#61]
![Screen Shot 2021-08-07 at 6 35 48 PM](https://user-images.githubusercontent.com/5014902/128615444-033c43e2-cd05-4ca3-8470-f51adcc39d13.png)
Anywhere "submit a support ticket" is mentioned, link to the support ticket page.

_Originally posted by @tesfaldet in https://github.com/mila-iqia/mila-docs/issues/46#issuecomment-894714056_

**Comment by fosterrath-mila** [comment]
It might be a good approach to include a URL to the ticketing system. Possibly also with pre-defined variables in the URL.

**Comment by achillemyette1** [comment]
Internal Issue -> GEN-1477
