### ISSUE TITLE
Add Google classroom links

### ISSUE THREAD

**Issue by satyaog** [mila-iqia/mila-docs#63]

**Comment by fosterrath-mila** [comment]
@priscillaben : Est-ce que tu pourrais SVP matérialiser une PR avec le url du classroom pour le cluster ? Merci  !

**Comment by achillemyette1** [comment]
@priscillaben est-ce que tu pourrais créer une tache pour le suivi ?

**Comment by satyaog** [comment]
Closing as discussed with @fosterrath-mila and @btravouillon
