### ISSUE TITLE
search does not work

### ISSUE THREAD

**Issue by gyom** [mila-iqia/mila-docs#66]
Try searching for anything in the search bar on the top left of the interface on 
[https://docs.mila.quebec](https://docs.mila.quebec).

I'm searching for absolutely obvious things and it's not returning any results. It's stuck at the "Searching ..." phase. I can't do basic things like search for "wandb" in the documentation.

I don't know if it's an option in sphinx that's not configured correctly, but right now this reduces the usefulness of our documentation.

**Comment by achillemyette1** [comment]
We were able to reproduce this. I will check this.

**Comment by achillemyette1** [comment]
will be fixed by https://github.com/mila-iqia/mila-docs/pull/67

**Comment by achillemyette1** [comment]
merged and fixed.
