### ISSUE TITLE
Update datasets form

### ISSUE THREAD

**Issue by vict0rsch** [mila-iqia/mila-docs#90]
The [form to request a dataset](https://docs.google.com/forms/d/e/1FAIpQLSf3XyKpvMaIHV2MaDBbFIVJCCcWLpo2HTjkQ94f-ebMRpY97Q/viewform) still mentions `miniscratch`

> If you need quick access to storage, note that you can use the /miniscratch volume (https://mila.docs.server.mila.quebec/cluster/mila-cluster/index.html#storage) for temporary space.

**Comment by btravouillon** [comment]
Thank you so much @vict0rsch. The form now mentions the new `scratch`.

![image](https://user-images.githubusercontent.com/14249095/141489288-0bf1e64d-26d2-4e1c-bff0-b79a393b8711.png)
