### ISSUE TITLE
Finding dataset on the home page of the docs

### ISSUE THREAD

**Issue by lavoiems** [mila-iqia/mila-docs#94]
Is there a page describing all the datasets on the cluster? Is this page easily available from the homepage: https://docs.mila.quebec/?

I am thinking about a table with dataset name and the absolute path on the cluster where we can find the dataset.

**Comment by btravouillon** [comment]
We can add the new website https://datasets.server.mila.quebec/ to the documentation. (https://datasets.mila.quebec/ might look better)
